/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JTextArea;

/**
 *
 * @author F.Carvalho / M. Hirose / V.Camargo
 */
public class CadastroEAlteracaoDadosAdicionaisMedicoView extends javax.swing.JDialog {

    /**
     * Creates new form CadastroEAlteracaoDadosAdicionaisMedicoView
     *
     * @param parent
     */
    public CadastroEAlteracaoDadosAdicionaisMedicoView(JFrame parent) {
        super(parent, true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPaciente = new javax.swing.JPanel();
        lblPaciente = new javax.swing.JLabel();
        panelOK2 = new javax.swing.JPanel();
        btnGravar2 = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        panelDadosAdicionais = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        boxFuma = new javax.swing.JComboBox<>();
        boxBebe = new javax.swing.JComboBox<>();
        boxColesterol = new javax.swing.JComboBox<>();
        boxDiabetes = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        scrollAlergias = new javax.swing.JScrollPane();
        txtAlergias = new javax.swing.JTextArea();
        scrollCirurgias = new javax.swing.JScrollPane();
        txtCirurgias = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelPaciente.setBackground(new java.awt.Color(255, 255, 255));

        lblPaciente.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        lblPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icone-paciente.png"))); // NOI18N
        lblPaciente.setText("Paciente");

        javax.swing.GroupLayout panelPacienteLayout = new javax.swing.GroupLayout(panelPaciente);
        panelPaciente.setLayout(panelPacienteLayout);
        panelPacienteLayout.setHorizontalGroup(
            panelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPaciente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPacienteLayout.setVerticalGroup(
            panelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPaciente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGravar2.setText("Gravar Dados");
        btnGravar2.setSelected(true);

        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout panelOK2Layout = new javax.swing.GroupLayout(panelOK2);
        panelOK2.setLayout(panelOK2Layout);
        panelOK2Layout.setHorizontalGroup(
            panelOK2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOK2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnGravar2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelOK2Layout.setVerticalGroup(
            panelOK2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOK2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelOK2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGravar2)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        panelDadosAdicionais.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Adicionais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel15.setText("Fuma:");

        jLabel22.setText("Bebe:");

        jLabel23.setText("Colesterol:");

        jLabel24.setText("Diabetes:");

        boxFuma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nao", "Sim" }));

        boxBebe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nao", "Sim" }));

        boxColesterol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nao", "Sim" }));

        boxDiabetes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nao", "Sim" }));

        jLabel28.setText("Alergias");

        jLabel29.setText("Cirurgias");

        txtAlergias.setColumns(20);
        txtAlergias.setLineWrap(true);
        txtAlergias.setRows(5);
        scrollAlergias.setViewportView(txtAlergias);

        txtCirurgias.setColumns(20);
        txtCirurgias.setLineWrap(true);
        txtCirurgias.setRows(5);
        scrollCirurgias.setViewportView(txtCirurgias);

        javax.swing.GroupLayout panelDadosAdicionaisLayout = new javax.swing.GroupLayout(panelDadosAdicionais);
        panelDadosAdicionais.setLayout(panelDadosAdicionaisLayout);
        panelDadosAdicionaisLayout.setHorizontalGroup(
            panelDadosAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosAdicionaisLayout.createSequentialGroup()
                .addGroup(panelDadosAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDadosAdicionaisLayout.createSequentialGroup()
                        .addComponent(scrollAlergias, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scrollCirurgias, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(panelDadosAdicionaisLayout.createSequentialGroup()
                        .addGroup(panelDadosAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDadosAdicionaisLayout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boxColesterol, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDadosAdicionaisLayout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boxFuma, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDadosAdicionaisLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 33, Short.MAX_VALUE)
                        .addGroup(panelDadosAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelDadosAdicionaisLayout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxBebe, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDadosAdicionaisLayout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxDiabetes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelDadosAdicionaisLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)))
                .addContainerGap())
        );
        panelDadosAdicionaisLayout.setVerticalGroup(
            panelDadosAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosAdicionaisLayout.createSequentialGroup()
                .addGroup(panelDadosAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel22)
                    .addComponent(boxFuma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxBebe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDadosAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(boxColesterol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxDiabetes))
                .addGap(18, 18, 18)
                .addGroup(panelDadosAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDadosAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollAlergias, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(scrollCirurgias))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelOK2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDadosAdicionais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDadosAdicionais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(panelOK2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxBebe;
    private javax.swing.JComboBox<String> boxColesterol;
    private javax.swing.JComboBox<String> boxDiabetes;
    private javax.swing.JComboBox<String> boxFuma;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGravar2;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JPanel panelDadosAdicionais;
    private javax.swing.JPanel panelOK2;
    private javax.swing.JPanel panelPaciente;
    private javax.swing.JScrollPane scrollAlergias;
    private javax.swing.JScrollPane scrollCirurgias;
    private javax.swing.JTextArea txtAlergias;
    private javax.swing.JTextArea txtCirurgias;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnGravar2() {
        return btnGravar2;
    }

    public JTextArea getTxtAlergias() {
        return txtAlergias;
    }

    public JTextArea getTxtCirurgias() {
        return txtCirurgias;
    }

    public JComboBox<String> getBoxBebe() {
        return boxBebe;
    }

    public void setBoxBebe(JComboBox<String> boxBebe) {
        this.boxBebe = boxBebe;
    }

    public JComboBox<String> getBoxColesterol() {
        return boxColesterol;
    }

    public void setBoxColesterol(JComboBox<String> boxColesterol) {
        this.boxColesterol = boxColesterol;
    }

    public JComboBox<String> getBoxDiabetes() {
        return boxDiabetes;
    }

    public void setBoxDiabetes(JComboBox<String> boxDiabetes) {
        this.boxDiabetes = boxDiabetes;
    }

    public JComboBox<String> getBoxFuma() {
        return boxFuma;
    }

    public void setBoxFuma(JComboBox<String> boxFuma) {
        this.boxFuma = boxFuma;
    }

}
