/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author mayza
 */
public class SelecaoPerfilView extends JFrame {

    /**
     * Creates new form SecretariaView2
     */
    public SelecaoPerfilView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        lblSelecionePerfil = new javax.swing.JLabel();
        btnSouMedico = new javax.swing.JButton();
        btnSouSecretaria = new javax.swing.JButton();
        btnGerenMsg = new javax.swing.JButton();
        lblSouMedico = new javax.swing.JLabel();
        lblSouSecretaria = new javax.swing.JLabel();
        lblGerenMsg = new javax.swing.JLabel();
        panelHeader = new javax.swing.JPanel();
        lblSaudeCIA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblSelecionePerfil.setText("Selecione seu Perfil:");

        btnSouMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icone-medico.png"))); // NOI18N
        btnSouMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSouMedicoActionPerformed(evt);
            }
        });

        btnSouSecretaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icone-secretaria.png"))); // NOI18N
        btnSouSecretaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSouSecretariaActionPerformed(evt);
            }
        });

        btnGerenMsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icone-msg.png"))); // NOI18N
        btnGerenMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenMsgActionPerformed(evt);
            }
        });

        lblSouMedico.setText("Sou Medico");

        lblSouSecretaria.setText("Sou Secretaria");

        lblGerenMsg.setText("Gerenciador de Mensagens");

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSelecionePerfil)
                .addContainerGap(488, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addComponent(btnSouMedico)
                        .addGap(35, 35, 35)
                        .addComponent(btnSouSecretaria)
                        .addGap(32, 32, 32)
                        .addComponent(btnGerenMsg))
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblSouMedico)
                        .addGap(78, 78, 78)
                        .addComponent(lblSouSecretaria)
                        .addGap(34, 34, 34)
                        .addComponent(lblGerenMsg)))
                .addGap(99, 99, 99))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSelecionePerfil)
                .addGap(18, 18, 18)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSouSecretaria)
                    .addComponent(btnSouMedico)
                    .addComponent(btnGerenMsg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSouMedico)
                    .addComponent(lblSouSecretaria)
                    .addComponent(lblGerenMsg))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelHeader.setBackground(new java.awt.Color(255, 255, 255));

        lblSaudeCIA.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        lblSaudeCIA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icone-consultorio.png"))); // NOI18N
        lblSaudeCIA.setText("Saude & CIA");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSaudeCIA)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSaudeCIA)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSouMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSouMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSouMedicoActionPerformed

    private void btnSouSecretariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSouSecretariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSouSecretariaActionPerformed

    private void btnGerenMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenMsgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGerenMsgActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerenMsg;
    private javax.swing.JButton btnSouMedico;
    private javax.swing.JButton btnSouSecretaria;
    private javax.swing.JLabel lblGerenMsg;
    private javax.swing.JLabel lblSaudeCIA;
    private javax.swing.JLabel lblSelecionePerfil;
    private javax.swing.JLabel lblSouMedico;
    private javax.swing.JLabel lblSouSecretaria;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelLogin;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnGerenMsg() {
        return btnGerenMsg;
    }

    public JButton getBtnSouMedico() {
        return btnSouMedico;
    }

    public JButton getBtnSouSecretaria() {
        return btnSouSecretaria;
    }
}
